<h1>
    <?php
        $this->headTitle()->append('navigation.index.imprint');
        echo $this->translate('view.index.imprint.heading');
    ?>
</h1>
<div class="container">
    <div class="col-lg-5">
        <?php echo $this->translate('view.application.imprintHtml'); ?>
    </div>

    <div class="col-lg-5">
        <?php echo $this->translate('view.application.liabilityExclusion'); ?><br />
    </div>
</div>