<h1>
    <?php
        $this->headTitle()->append('navigation.account.settings');
        echo $this->translate('view.account.settings.heading');
    ?>
</h1>
<p>
    <?php echo $this->translate('view.account.settings.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php echo $this->formDecorator($this->form); ?>
</div>